Health-Union/dbt-xdb

test_xdb/models/under_test/schema.yml
test_xdb/models/under_test/using_test.sql
xdb/macros/using.sql

Supports `using(relation_1, relation_2, column_name)` as a simple alias for 
```
relation_1 
JOIN
relation_2 
ON 
relation_1.column_name = relation_2.column_name
```

Adds a very simple USING macro

---

.gitignore
README.md
docs/macros.md
test_xdb/scripts/macrodocs.py
test_xdb/scripts/test_run.py

this is pretty far off the reservation and I apologize. but it was driving me nuts that we have zero automated documentation here and I feel like it was worth the slight trip off the beaten path.
This helper script builds a markdown macros.md index from jinja docstrings. This lets us write normal docstrings in the macros and have clean docs - which I feel like we really need if people will be using this as a utility class. 
I added the docs build into the test suite so every test run also builds the docs. That may not be the most appropriate place for this really. but I'm experimenting here. 
check out the docs generated at `/docs/macros.md`, and the docstrings that make them in the `datediff` macro.

Creates autodocs from comments

---

docs/macros.md
macros/datediff.sql
test_xdb/models/under_test/datediff_test.sql
test_xdb/models/under_test/schema.yml

because we use `DATEDIFF('quarter',a,b)` a lot
will calculate the gregorian quarter diff between 2 dates. 
passes integration tests in snowflake, postgres and BigQuery

adds "quarter" support to DATEDIFF

---

macros/cast_timestamp.sql
test_xdb/models/under_test/schema.yml

while working on datediff I found that PG and Snowflake were casting UTC differently - PG was casting the value _as_ UTC, while snowflake was casting it as local time and then converting it to UTC... no Bueno. 
This fixes the two so they cast exactly the same, and adds the disappeared test coverage.

Fixes conflict in how PG and Snowflake cast

---

docs/macros.md
macros/interval_to_timestamp.sql
test_xdb/models/under_test/interval_to_timestamp_test.sql
test_xdb/models/under_test/schema.yml

Adding interval_to_timestamp macro to allow for converting a unit of time (seconds, minutes) into a time stamp (ex. 10000 seconds -> 02:46:40)

interval_to_timestamp

---

macros/dateadd.sql
macros/datediff.sql
macros/timeadd.sql

Adding parenthesis to allow some datediff, dateadd and timeadd to be used inside one another.
* Added parenthesis around parts of code
* They will now be allow to use datediff, dateadd and timeadd within other UDF's.

Add Parenthesis to datediff, dateadd and timeadd

---

docs/macros.md
macros/concat.sql
test_xdb/models/schema_tests/concat.yml
test_xdb/models/under_test/concat_test.sql

This gives concat the option to treat nulls as strings, or pass them directly to the target. Default is now to convert them and preserve the concat'd string. 
* `convert_null` defaults to True. When set to False `NULL` will be passed directly. 
#40  ✔️  
This is a _breaking_ change, if you depended on the old default NULL behavior it will need to be explicitly set now.

Changes how concat treats NULL values

---

macros/fold.sql
macros/utilities/strip_to_single_line.sql
test_xdb/models/schema_tests/fold.yml
test_xdb/models/under_test/fold_test.sql
test_xdb/profiles.yml

This adds the ability to flat "fold" values to match the natural folding of the RDBMS. in Postgres unquoted things default to lowercase, this makes them lowercase. in Snowflake it makes them uppercase.
* adds fold macro
* cleans up how the `strip_to_single_line` macro scrubs comments and newlines
makes it easy to deal with db casing. note that this doesn't quote things - so it can be used for identifiers OR strings! 
This closes #24 

updated strip and added fold

---

Dockerfile

We allowed the DBT version to float in the dockerfile until now. 
DBT is pinned at v0.17.1-rc4
At the moment this version represents the stable build (0.17.0) + regression fixes XDB needs to function (namely data type introspection in schema test accepted_values)
*Note*: we should def consider using a cyclical build for deployment testing (maybe TOX based?) that rotates dbt versions and tags each supported version :) 

Pins to DBT v0.17.1-rc4

---

macros/recursive_cte.sql
test_xdb/models/schema_tests/recursive_cte.yml
test_xdb/models/under_test/recursive_cte.sql

This update adds the recursive_cte macros
* The recursive_cte macro now works!
* They can now use recursive_cte's in postgres and snowflake (bigquery does not support recursive cte's)
- [ x] does `docker-compose exec testxdb test` run successfully?
- [ x] does `docker-compose exec testxdb docs` build docs without errors?
- [ x] does `docker-compose exec testxdb coverage` pass coverage standards?
- [ x] did you leave the codebase better than you found it? 

Updated to include recrusive_cte macro with tests

---

macros/generate_daily_time_series_values.sql

Updates to generate_daily_time_series_values macro:
1. Match behavior of postgres by outputting timestamps (instead of dates) in ascending order
2. Use row_number() approach to generating sequence so as to avoid possibility of gaps in sequence, As described here: https://docs.snowflake.com/en/sql-reference/functions/seq1.html
Postgres and Snowflake tests pass

Updates to generate_daily_time_series_values macro

---

macros/extract_json_path.sql
macros/json_extract_path_text.sql
test_xdb/models/schema_tests/json_extract_path_text_test.yml
test_xdb/models/schema_tests/split_test.yml
test_xdb/models/under_test/json_extract_path_text_test.sql
test_xdb/models/under_test/split_test.sql

Adds a new macro to essentially use `json_extract_path_text` across DBs.
* added `xdb.json_extract_path_text` macro with snowflake and postgres support
* fixed failing `split` macro test

Add simple json field extraction

---

Dockerfile
macros/generate_uuid.sql
test_xdb/models/schema_tests/generate_uuid_test.yml
test_xdb/models/under_test/generate_uuid_test.sql
test_xdb/scripts/gather_targets.py
test_xdb/scripts/test_setup.py

Allows the generation of UUID (v4) values across different DBs
* `generate_uuid` macro was added with support for snowflake and postgres
* updated test setup to add necessary extension (`uuid-ossp`) to postgres
* More cross database support is always better

UUID generator

---

docs/macros.md
macros/cast_json.sql
macros/json_extract_path_text.sql
test_xdb/models/schema_tests/cast_json.yml
test_xdb/models/under_test/cast_json_test.sql
test_xdb/models/under_test/json_extract_path_text_test.sql

This adds a simple function to cast/parse a string into the appropriate json datatype since there isn't a uniform way to do that.
* The `cast_json` macro is added for snowflake and postgres
* Types returned are the appropriate datatypes for `json_extract_path_text` macro
* Postgres returns the basic `json` datatype
* Snowflake returns a `variant` datatype
* Better cross database json support

Adds basic parse/cast to json datatype

---

docs/macros.md
test_xdb/models/under_test/split_test.sql

Added a split test for bigquery
Checked bigquery tests with `docker-compose exec testxdb test` and generated new docs with `docker-compose exec testxdb docs` (also ran coverage).
Allows split macro to be used in bigquery.

added split test for bigquery

---

docs/macros.md
macros/percent_change.sql
macros/relative_change.sql
test_xdb/models/schema_tests/percent_change.yml
test_xdb/models/schema_tests/relative_change_test.yml
test_xdb/models/under_test/percent_change_test.sql
test_xdb/models/under_test/relative_change_test.sql

Adds a `relative_change` and `percent_change` arithmetic helper functions

Added relative/percent change helper macros

---

macros/concat.sql
test_xdb/models/schema_tests/concat.yml
test_xdb/models/under_test/concat_test.sql

FIxes an edge case where casting as a varchar generated `NULL` columns to concatenate (when explicitly set to concat `NULL`s as the varchar `'NULL'`)
Only known case is a json typed `'null'` value in Snowflake where casting changes a SQL `is NULL` check.
``` SQL
select 
parse_json('{"key":"value","key2":null}'):key2 is null as in_object_null_check
, parse_json('{"key":"value","key2":null}'):key2::varchar is null as in_object_null_varchar_check
, parse_json('null') is null as object_null_check
, parse_json('null')::varchar is null as object_null_varchar_check
```
* added a test for the edge case (only happens in snowflake)
* the concat `NULL` check happens on the casted column value instead of the raw column value
* Should fix an edge case without changing the normal behavior of `concat`

Fix concat null edge case 

---

docs/macros.md
macros/get_email_domain_extension.sql
test_xdb/models/schema_tests/get_email_domain_extension.yml
test_xdb/models/under_test/get_email_domain_extension_test.sql

A function that returns the domain extension of an email address (e.g. 'com', 'net', 'co.uk')
First release.
Developers can easily retrieve the domain extension of an email address is both Postgre and Snowflake.

First release of get_email_domain_extension.

---

docs/macros.md
macros/env_generate_schema_name.sql

_The env_generate_schema_name general macro was added._
* _The new generic macro was introduced - env_generate_schema_name, it generates the schema name based on the current environment_
* _it will be used in the datascience, datawarehouse and datalake repos_
- [Y] does `docker-compose exec testxdb test` run successfully?
- [Y ] does `docker-compose exec testxdb docs` build docs without errors?
- [Y ] does `docker-compose exec testxdb coverage` pass coverage standards?
- [ Y] did you leave the codebase better than you found it? 

DATA-2618: the env_generate_schema_name macro was added

---

docs/macros.md
macros/cast_timestamp.sql
macros/timeadd.sql
test_xdb/models/under_test/timeadd_test.sql

* refinement of logic of timeadd() and cast_timestamp() macros
* addition of new argument timestamp_cast_flag to timeadd() macro
* update of corresponding tests
* update of timeadd() macro helps to fix the issue with timezones in https://bitbucket.org/healthunion/hu-dw-datawarehouse/pull-requests/365 against Snowflake and Postgres targets
- [*] does `docker-compose exec testxdb docs` build docs without errors?
- [*] does `docker-compose exec testxdb coverage` pass coverage standards?
- [*] did you leave the codebase better than you found it? 

feature/data 3045 Update of timeadd() macro

---

docker-compose.yml
docs/macros.md
macros/swap_schema.sql
test_xdb/models/schema_tests/swap_schema_test.yml
test_xdb/models/under_test/generate_uuid_test.sql
test_xdb/models/under_test/swap_schema_test.sql
test_xdb/scripts/gather_targets.py
test_xdb/scripts/test_setup.py

This PR is about adding of new macro swap_schema(), which is able to swap the names between two specified schemas. It can be easily used (by `dbt run-operation` commands) as a part of potential Blue/Green Deploy of dbt projects.
* _this adds new macro swap_schema() and corresponding tests to it._
* _this updates `profiles.yml` to make local testing process more comfortable._
* _this adds supportive hooks to `generate_uuid_test` model that fix testing of corresponding macro on Postgres target._
* _this provides new options for organisation of Blue/Green Deploy of dbt projects._
- [+] does `docker-compose exec testxdb test` run successfully?
- [+] does `docker-compose exec testxdb docs` build docs without errors?
- [+] does `docker-compose exec testxdb coverage` pass coverage standards?
- …

Adding of new macro swap_schema(), minor common updates and fixes.

---

docs/macros.md
macros/override_ref.sql
test_xdb/models/schema_tests/override_ref_test.yml
test_xdb/models/schema_tests/override_ref_with_swap_schema_test.yml
test_xdb/models/under_test/override_ref_test.sql
test_xdb/models/under_test/override_ref_test_model_table.sql
test_xdb/models/under_test/override_ref_test_model_view_based_on_table.sql
test_xdb/models/under_test/override_ref_test_model_view_based_on_view.sql
test_xdb/models/under_test/override_ref_with_swap_schema_test.sql
test_xdb/profiles.yml

_This PR adds `override_ref()`, which behaves as builtin macro `ref()`, but omits database and schema rendering in references of views (this behaviour for Snowflake target only). It is supposed to be used as override version of `ref()` in pair with `swap_schema()` macro as a part of potential Blue/Green Deploy of dbt projects._
* _this adds new macro `override_ref()` and corresponding models and tests to it._
* _this changes Postgres testing schema's name in `profiles.yml` to make testing process more comfortable and unified._
* _this adds supportive model `override_ref_with_swap_schema_test.sql` and corresponding test which help to test work of `override_ref()` and `swap_schema()` macros in pair._
* _this provides new options for organisation of Blue/Green Deploy of dbt projects._
* _in …

Adding of override_ref() macro

---

docs/macros.md
macros/drop_schema.sql
test_xdb/models/schema_tests/drop_schema_test.yml
test_xdb/models/under_test/drop_schema_test.sql

_This PR adds `drop_schema()`, which drops schema named as `schema_name` and all its objects. The macro is supposed as a part of potential Blue/Green Deploy of dbt projects._
* _this adds new macro `drop_schema()` and corresponding models and tests for it._
* _this provides new options of data management might be useful for organisation of Blue/Green Deploy of dbt projects._
- [ + ] does `docker-compose exec testxdb coverage` pass coverage standards?
- [ + ] did you leave the codebase better than you found it? (Hope so.)

Adding of drop_schema() macro

---

docs/macros.md
macros/clone_schema_grants.sql
test_xdb/models/schema_tests/clone_schema_grants_test.yml
test_xdb/models/under_test/clone_schema_grants_test.sql
test_xdb/models/under_test/swap_schema_test.sql

_This PR adds `clone_schema_grants()`, which replaces existing grants on schema `schema_two` by ones on schema `schema_one`. The macro is supposed as a part of potential Blue/Green Deploy of dbt projects._
* _this adds new macro `clone_schema_grants()` and corresponding model and tests to it._
* _this provides new function of privileges propagation might be useful for organisation of Blue/Green Deploy of dbt projects._
- [ + ] does `docker-compose exec testxdb coverage` pass coverage standards?
- [ + ] did you leave the codebase better than you found it? 

adding of clone_schema_grants() macro and corresponding stuff to it

---

macros/current_timestamp.sql
macros/current_timestamp_ntz.sql
macros/like_any.sql
test_xdb/models/schema_tests/current_timestamp_ntz_test.yml
test_xdb/models/schema_tests/current_timestamp_test.yml
test_xdb/models/schema_tests/like_any_test.yml
test_xdb/models/schema_tests/schema.yml
test_xdb/models/under_test/current_timestamp_ntz_test.sql
test_xdb/models/under_test/current_timestamp_test.sql

Macroses for current_timestamp and current_timestamp_ntz for Snowflake and Posgtres systems
Add 2 new macroses
Add more functionality
- [+] does `docker-compose exec testxdb test` run successfully?
- [+] does `docker-compose exec testxdb docs` build docs without errors?
- [+] does `docker-compose exec testxdb coverage` pass coverage standards?
- [+] did you leave the codebase better than you found it? 

Data 4788 xdb add appropriate variants of now macros

---

macros/clone_schema_grants.sql

_It is an update of clone_schema_grants macro that fixes this issue - https://cloud.getdbt.com/deploy/159/projects/3671/runs/182632469_
* _commands generator inside the macro has an additional logic that allows it to handle granting to database role now._
* _this makes the bug in https://cloud.getdbt.com/deploy/159/projects/3671/runs/182632469 not a bug!_
- [+] does `docker-compose exec testxdb test` run successfully?
- [+] does `docker-compose exec testxdb docs` build docs without errors?
- [+] does `docker-compose exec testxdb coverage` pass coverage standards?
- [+] did you leave the codebase better than you found it? 
- This run proves that this updates work - https://cloud.getdbt.com/deploy/159/projects/3671/runs/182694836.
@Health-Union/hu-data make sure to include a version tag in …

feature/data 5444 Update clone_schema_grants to handle granting to database role

---

macros/clone_schema.sql
test_xdb/models/under_test/clone_schema_tables_data_equality_test.sql
test_xdb/models/under_test/clone_schema_test.sql

_this PR is devoted to fix an issue related to work of clone_schema macro._
* _changes a generation of grant commands in clone_schema macro and updates related stuff._
* _this makes the B/G Deploy mechanism not missing select privilege on PROD schema to DATA_WAREHOUSE_PROD_READER_DB_ROLE_
- [ + ] does `docker-compose exec testxdb coverage` pass coverage standards?
- [ + ] did you leave the codebase better than you found it? 

Feature/data 5529 Update of clone_schema macro

---

docs/macros.md
macros/clone_schema.sql
macros/swap_schema.sql
test_xdb/models/under_test/clone_schema_tables_data_equality_test.sql
test_xdb/models/under_test/clone_schema_test.sql

_This PR makes behaviour of `clone_schema` macro more consistent across Postgres and Snowflake implementations._
_Now `clone_schema` macro copies views and functions respecting to `comment_tag` argument's input in both implementations._
_This update makes behaviour of `clone_schema` macro more general and consistent. This update also allows us to use it safely without `comment_tag` with `PROD` and `STAGE` schemas.
Examples of the new version's successful applying:_
_1. w `comment_tag` flag - https://cloud.getdbt.com/deploy/159/projects/3671/runs/236891093_
_2. w/o `comment_tag` flag - https://cloud.getdbt.com/deploy/159/projects/3671/runs/236891174_ …

Generalising of implementation of clone_schema() macro.

---

docs/macros.md
macros/clone_schema.sql
test_xdb/scripts/test_run.py

* _This PR makes clone_schema() macro copy views across the schemas correctly._
* _This PR makes clone_schema() macro handle a schema names with database names as an arguments (for Snowflake DB)._
* _This PR makes clone_schema() macro safer in some use cases._
* _It contains a clone_schema() macro code changes._
* _It enables an additional tests for a clone_schema() macro calls in the pipeline._
* _It could allow users to use this functionality correctly without `comment_tag` argument passing._
* _It could make using to this functionality a bit safer from the data keeping perspective._
- [ + ] does `docker-compose exec testxdb coverage` pass coverage …

feature/data 7285 Updates of the clone_schema() macro.
